// Generated by https://quicktype.io

export interface AccountsInfo {
  cuentas: Account[]
  cuestas: Cuesta[]
}

export interface Account {
  e: string
  n: string | number
  t: string
  id: number | string
  saldo: string
  moneda: string
  tipo_letras: string
}

export interface Cuesta {
  id: number
  nombre: string
}
